<?php

function pum_civicrm_views_views_api() {
  return array('api' => 3.0);
}


function pum_civicrm_views_enable() {
  $maxWeight = db_query("SELECT MAX(weight) FROM {system} where type = 'module' AND (name = 'civicrm' OR  name = 'views') ")->fetchField();
  $maxWeight++;
  
  //make sure that our module has a higher weight than the civicrm and civicrm_entity module
  //if not our changes to the available fields for views wont occur
  //because the hook should be runned after the civicrm and civcirm_entity has runned their relevant hooks
    db_update('system')
    ->fields(array('weight' => $maxWeight))
    ->condition('type', 'module')
    ->condition('name', 'pum_civicrm_views')
    ->execute();
}